version: "3.9"
services:
  nginx:
    restart: always
    image: linuxserver/letsencrypt
    volumes:
      - ./vnginx:/config
    ports:
      - "188.68.62.150:80:80"
      - "188.68.62.150:443:443"
    environment:
      - URL=suggest-app.com
      - SUBDOMAINS=dev
      - EXTRA_DOMAINS=portfolio-rebalancer.de,portfolio-rebalancer.com
    networks:
      - jitcom_net

networks:
  jitcom_net:
    external: true
